# Generated by Django 4.1.4 on 2023-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='label',
            field=models.TextField(default='PlaceHolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='share_link',
            field=models.TextField(default='PlaceHolder'),
            preserve_default=False,
        ),
    ]
