# Generated by Django 4.1.4 on 2023-01-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
