# Generated by Django 4.1.4 on 2023-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_favorite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
