# Generated by Django 4.1.4 on 2023-02-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_favorite_image_favorite_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
